### ISSUE TITLE
你好，问一下有没有在app store connect 配置内购的相关教程啊

### ISSUE THREAD

**Issue by tzgd** [dgynfi/DYFStoreKit_Swift#3]
目前查到的配置教程与现有的界面相差得很大，感觉都没法使用

我卡在了付费协议没法点击  同意不了

**Comment by itenfay** [comment]
配置内购分三个步骤：

- 填写收款银行账号
填写收款银行账号信息，若遇到按钮点击不了，就某些信息改成英文试一下，比如Adress等，[联行号和地址查询系统（CNAPS大额行号查询）]( https://www.tui78.com/bank/)

- 配置税务信息
配置税务信息按America那边默认填写就行，不懂的部分Google一下。

- 配置内购产品(Metadata)
创建内购产品，包括产品id、定价Level、描述和审核图(提供手机尺寸大小的)，分为消耗类和非消耗类产品，非消耗类的分为续期自动订阅和非续期订阅。

**Comment by tzgd** [comment]
> 配置内购分三个步骤：
> 
> * 填写收款银行账号
>   填写收款银行账号信息，若遇到按钮点击不了，就某些信息改成英文试一下，比如Adress等，[联行号和地址查询系统（CNAPS大额行号查询）](https://www.tui78.com/bank/)
> * 配置税务信息
>   配置税务信息按America那边默认填写就行，不懂的部分Google一下。
> * 配置内购产品(Metadata)
>   创建内购产品，包括产品id、定价Level、描述和审核图(提供手机尺寸大小的)，分为消耗类和非消耗类产品，非消耗类的分为续期自动订阅和非续期订阅。

好的，多谢了 已经搞定了
