### ISSUE TITLE
非常赞👍🏻，但是有一个小建议💡

### ISSUE THREAD

**Issue by HouWan** [dgynfi/DYFStoreKit_Swift#4]
作者写的`DYFStore`框架非常不错，各种情况都考虑到了，不过我有一个小小的建议就是，在阅读源码的过程中，感觉作者是把`OC`简单翻译成`Swift`而已，其实如果纯粹`Swift`写的话，代码量可以精简非常多。

例如使用的都是`OC`的`NSMutableArray`，而不是Swift自己的`Array`，

例如`DYFStore.swift`文件里面的
```swift
public func product(forIdentifier productIdentifier: String) -> SKProduct? {
    var product: SKProduct? = nil
    for e in self.availableProducts {
        let aProduct = e as! SKProduct
        let id = aProduct.productIdentifier
        if id == productIdentifier {
            product = aProduct
            break
        }
    }
    return product
}
```

这个方法，如果更加Swift的写法是：
```swift
public func product(forIdentifier productIdentifier: String) -> SKProduct? {
    // 当然，需要将 availableProducts 的元素声明泛型或者直接使用Swifit的数组
    availableProducts.first { $0.productIdentifier == productIdentifier }
}
```

**Comment by itenfay** [comment]
> 作者写的`DYFStore`框架非常不错，各种情况都考虑到了，不过我有一个小小的建议就是，在阅读源码的过程中，感觉作者是把`OC`简单翻译成`Swift`而已，其实如果纯粹`Swift`写的话，代码量可以精简非常多。
> 
> 例如使用的都是`OC`的`NSMutableArray`，而不是Swift自己的`Array`，
> 
> 例如`DYFStore.swift`文件里面的
> 
> ```swift
> public func product(forIdentifier productIdentifier: String) -> SKProduct? {
>     var product: SKProduct? = nil
>     for e in self.availableProducts {
>         let aProduct = e as! SKProduct
>         let id = aProduct.productIdentifier
>         if id == productIdentifier {
>             product = aProduct
>             break
>         }
>     }
>     return product
> }
> ```
> 
> 这个方法，如果更加Swift的写法是：
> 
> ```swift
> public func product(forIdentifier productIdentifier: String) -> SKProduct? {
>     // 当然，需要将 availableProducts 的元素声明泛型或者直接使用Swifit的数组
>     availableProducts.first { $0.productIdentifier == productIdentifier }
> }
> ```

感谢你的反馈！

这个库写得比较早，主要是考虑兼容OC项目，可以后续优化一下。

**Comment by itenfay** [comment]
@HouWan 已经更新到2.3.0版本
